accounts/urls.py
from django.conf.urls import patterns, url

urlpatterns = patterns('',
    (r'^login/$',
     'django.contrib.auth.views.login',
     {'template_name': 'accounts/login.html'}),

    (r'^logout/$',
     'django.contrib.auth.views.logout',
     {'template_name': 'accounts/logged_out.html'}),

    (r'^password_change/$',
     'django.contrib.auth.views.password_change',
     {'template_name': 'accounts/password_change_form.html'}),

    (r'^password_change/done/$',
     'django.contrib.auth.views.password_change_done',
     {'template_name': 'accounts/password_change_done.html'}),

    (r'^password_reset/$',
     'django.contrib.auth.views.password_reset',
     {'template_name': 'accounts/password_reset_form.html',
      'email_template_name': 'accounts/password_reset_email.html'}),

    (r'^password_reset/done/$',
     'django.contrib.auth.views.password_reset_done',
     {'template_name': 'accounts/password_reset_done.html'}),

    (r'^reset/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
     'django.contrib.auth.views.password_reset_confirm',
     {'template_name': 'accounts/password_reset_confirm.html'}),

    (r'^reset/done/$',
     'django.contrib.auth.views.password_reset_complete',
     {'template_name': 'accounts/password_reset_complete.html'}),

    (r'^signup/$',
     'accounts.views.signup',
     {'template_name': 'accounts/signup_form.html',
      'email_template_name': 'accounts/signup_email.html'}),

    (r'^signup/done/$',
     'accounts.views.signup_done',
     {'template_name': 'accounts/signup_done.html'}),

    (r'^signup/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',
     'accounts.views.signup_confirm'),

    (r'^signup/complete/$',
     'accounts.views.signup_complete',
     {'template_name': 'accounts/signup_complete.html'}),
)

samalinews_com/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from accounts.forms import ProfileForm
from defaultapp.feeds import LatestArticles

from samalinews_com import settings

#import filebrowser.sites

admin.autodiscover()

feeds = { 'latest' : LatestArticles }

urlpatterns = patterns('',
    url(r'^$', 'defaultapp.views.home', name='home'),
    url(r'^article/(?P<sl>[-\w]+)/$', 'defaultapp.views.show_article', name='article'),
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    url(r'^admin/', include(admin.site.urls)),

    url(r'^tinymce/', include('tinymce.urls')),

    (r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes': True}),

    url(r'^categories/([-\w]+)/$', 'defaultapp.views.show_category', name='category'),
    url(r'^tags/([-\w]+)/$', 'defaultapp.views.tag', name='tag'),
    url(r'^latest/', 'defaultapp.views.show_latest'),
    url(r'^popular/', 'defaultapp.views.show_popular'),

    url(r'^accounts/', include('registration.backends.default.urls')),
    url(r'^profiles/edit/$', 'profiles.views.edit_profile', {'form_class': ProfileForm}, 'profiles_edit_profile'),
    url(r'^profiles/', include('profiles.urls')),

    url(r'^search/', 'defaultapp.views.search_article', name="search_article"),
    
    url(r'^comments_app/add_comment', 'comments_app.views.add_comment'),
    
    url(r'^rss/(?P<url>.*)/$', LatestArticles()),

)

accounts/models.py
from django.db import models
from django.contrib.auth.models import User
from phonenumber_field.modelfields import PhoneNumberField
from django.db.models.signals import post_save

class UserProfile(models.Model):
    user = models.OneToOneField(User)
    phone_number = PhoneNumberField(null=True, blank=True)
    date_of_birth = models.DateField(null=True, blank=True)
    career = models.CharField(max_length=80, blank=True)
    def __unicode__(self):
        return u'%s %s' % (self.user.first_name, self.user.last_name)
    def get_absolute_url(self):
        return ('profiles_profile_detail', (), { 'username': self.user.username })
    get_absolute_url = models.permalink(get_absolute_url)


def create_user_profile(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)

post_save.connect(create_user_profile, sender=User)

templates/profiles/edit_profile.html
{% extends "base.html" %}

{% block content %}
<div class="well">
    <h3>Editing profile</h3>
    <form method="post" action="">
        {% csrf_token %}
        {% if form.non_field_errors %}
            <div class="alert alert-error">{{ form.non_field_errors }}</div>
        {% endif %}
        {% for field in form %}
            <p>
                {{ field.label_tag }} {{ field }}
                {% if field.errors %}
                	    <div class="alert alert-error">{{ field.errors }}</div>
                {% endif %}
            </p>
        {% endfor %}
        <p><input class="btn" type="submit" value="Save profile" /></p>
    </form>
</div>
{% endblock %}

templates/profiles/profile_detail.html
{% extends "base.html" %}

{% block title %} {{ user.first_name }} {{ user.last_name }}{% endblock %}

{% block content %}
<div class='well'>
    {% ifequal user profile.user %}
        <p><h3>My profile<a class="edit_profile" href="{% url profiles_edit_profile %}" class="button"> Edit</a></h3></p>

        <p>
            <p><b>Email:</b></p>  
            <i class="icon-envelope"></i>  {{ user.email }}
        </p>

		{% if profile.phone_number %}
        <p>
            <b>Phone number: </b>
            <label id="phone_number">{{ profile.phone_number }}</label>
        </p>
        {% endif %}

    {% else %}
        <p>Profile of {{ profile.user.username }}</p>
    {% endifequal %}

	{% if profile.date_of_birth %}
    <p>
        <b>Date of birth: </b>
        <label>{{ profile.date_of_birth }}</label>
    </p>
    {% endif %}

	{% if profile.career %}
    <p>
        <b>Career: </b>
        <label id="id_career">{{ profile.career }}</label>
    </p>
    {% endif %}
	
	{% if user.first_name %}
    <p>
        <b>First name</b>
        <label id="id_first_name">{{ user.first_name }}</label>
    </p>
    {% endif %}

	{% if user.last_name %}
    <p>
        <b>Last name</b>
        <label id="id_last_name">{{ user.last_name }}</label>
    </p>
    {% endif %}

</div>

{% endblock content %}